script

diff --git a/socket/event/proxy/scripts/customerlive b/socket/event/proxy/scripts/customerlive
--- a/socket/event/proxy/scripts/customerlive
+++ b/socket/event/proxy/scripts/customerlive
@@ -22,17 +22,18 @@ url="http://open.life.qq.com/customerlive.php"
 start()
 {
     [ -x $server ] || exit 1
+    echo  > $pid_file || echo "pid file $pid_file access denied"
     echo "Starting $servername :"
     $server -c$client_port -r$rpc_port -l$log_file -p$pid_file -t$thread_num -u$url -d
     sleep 1
-    [ -f $pid_file ] && echo "$servername started"
+    [ ! -s $pid_file ] || echo "$servername failed to start"
 }
 
 stop()
 {
     echo "Stoping $servername: "
-    cat $pid_file | xargs kill
-    rm -f $pid_file
+    [ -s $pid_file ] && cat $pid_file | xargs kill
+    echo > $pid_file
 }
 
 case $1 in
